# src/fishviz/data.py

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import json
import unicodedata
from typing import Any

import pandas as pd


# ----------------------------
# Normalization helpers
# ----------------------------

def normalize_text(value: Any) -> str:
    """
    Normalize text values for reliable joins/matching:
    - Unicode normalization (NFKC)
    - Trim whitespace
    - Casefold (better than lower() for case-insensitive matching)
    """
    if value is None or (isinstance(value, float) and pd.isna(value)):
        return ""
    return unicodedata.normalize("NFKC", str(value)).strip().casefold()


# ----------------------------
# Core transformations
# ----------------------------

def calculate_fish_counts(df: pd.DataFrame, group_by: list[str]) -> pd.DataFrame:
    return df.groupby(group_by).size().reset_index(name="Fish Count")


def pivot_species_data(df: pd.DataFrame) -> pd.DataFrame:
    """
    Wide table: one row per Zone, one column per Species, values = fish counts.
    """
    species_counts = df.groupby(["Zone", "Species"]).size().reset_index(name="Fish Count")
    return (
        species_counts.pivot(index="Zone", columns="Species", values="Fish Count")
        .fillna(0)
        .reset_index()
    )


def load_geojson(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def load_and_clean_fish_csv(path: Path) -> pd.DataFrame:
    df = pd.read_csv(path, low_memory=False)

    # Parse and filter dates
    df["Date"] = pd.to_datetime(df["Date"], format="%d-%m-%Y", errors="coerce")
    df = df[df["Date"].notna()].copy()

    # Derived time columns
    df["Year"] = df["Date"].dt.year
    df["Month"] = df["Date"].dt.month

    # Normalize key string columns used across the app
    for col in ["Zone", "Water Body", "Species", "Bait", "Fin Clip"]:
        if col in df.columns:
            df[col] = df[col].apply(normalize_text)

    return df


# ----------------------------
# Bundle returned to the app
# ----------------------------

@dataclass(frozen=True)
class DataBundle:
    df: pd.DataFrame
    summary_df: pd.DataFrame
    species_pivot: pd.DataFrame
    geojson: dict


def load_bundle() -> DataBundle:
    """
    Single entrypoint to load everything the app needs.
    Assumes:
      - data/raw/fish.csv
      - data/processed/normalized_creeks.geojson (generated by scripts/normalize_geojson.py)
    """
    repo_root = Path(__file__).resolve().parents[2]

    csv_path = repo_root / "data" / "raw" / "fish.csv"
    geojson_path = repo_root / "data" / "processed" / "normalized_creeks.geojson"

    geojson = load_geojson(geojson_path)
    df = load_and_clean_fish_csv(csv_path)

    # Summary table used by many charts
    summary_df = calculate_fish_counts(
        df,
        ["Year", "Zone", "Species", "Water Body", "Bait", "Fin Clip", "Month", "Length", "Name"],
    )

    # Avoid the "dropna breaks alignment" bug
    summary_df = summary_df.dropna(subset=["Length", "Name"]).copy()

    # Add zone-level + water-body-level counts back onto df
    zone_counts = calculate_fish_counts(df, ["Zone"])
    water_body_counts = calculate_fish_counts(df, ["Water Body"])

    df = df.merge(zone_counts, on="Zone", how="left").merge(
        water_body_counts,
        on="Water Body",
        how="left",
        suffixes=("_Zone", "_WaterBody"),
    )

    species_pivot = pivot_species_data(df)

    return DataBundle(
        df=df,
        summary_df=summary_df,
        species_pivot=species_pivot,
        geojson=geojson,
    )